# Generated by Django 6.0.6 on 2026-06-29 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ranking_details', models.CharField(blank=True, help_text="e.g., '4th Rank out of 500 participants'", max_length=150)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=150)),
                ('issue_date', models.CharField(max_length=100)),
                ('credential_link', models.URLField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=150)),
                ('branch', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=100)),
                ('academic_journey', models.TextField(help_text='Description of your academic accomplishments')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('duration', models.CharField(help_text="e.g., 'July 2024 - Present' or 'Jan 2024 - Jun 2024'", max_length=100)),
                ('description', models.TextField(help_text='Newline-separated list of responsibilities/achievements')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Short description for the project grid card')),
                ('detailed_description', models.TextField(help_text='Comprehensive details for the project modal')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('tech_stack', models.CharField(help_text="Comma-separated values (e.g., 'Django, Python, PostgreSQL, Docker')", max_length=255)),
                ('key_features', models.TextField(help_text='Newline-separated list of key features')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_demo_link', models.URLField(blank=True, null=True)),
                ('architecture_diagram', models.ImageField(blank=True, null=True, upload_to='architecture/')),
                ('challenges_faced', models.TextField(blank=True)),
                ('future_improvements', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('languages', 'Programming Languages'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('ai_development', 'AI Development'), ('devops', 'DevOps'), ('computer_science', 'Computer Science')], max_length=30)),
                ('proficiency', models.IntegerField(help_text='Proficiency percentage (e.g. 90)')),
                ('icon_class', models.CharField(blank=True, help_text="Devicon/FontAwesome class (e.g., 'devicon-python-plain colored')", max_length=100)),
                ('icon_svg', models.TextField(blank=True, help_text='Raw SVG XML code for custom icons')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_screenshots/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='portfolio.project')),
            ],
        ),
    ]
